// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sozvixrdzbznhekzudrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvenZpeHJkemJ6bmhla3p1ZHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzY4MzEsImV4cCI6MjA3MDYxMjgzMX0.e-gHJp0xnUjnGZVPszcgwLo2C7BIBDPoNfEUOViEfUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});